---
title: "tab2 plotting"
author: "Yingfei Jiang"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
```

```{r}
veggie_raw<-read_csv("veggies.csv")
meat_raw<-read_csv("meat.csv")
```

```{r}
cheese_percent <- 0.249
cheese_cf_kg<- 0.1/cheese_percent #ef/cheese_cf_kg => ef(kg CO2e/kg) 
fish_percent <- 0.17 #cod, http://www.fao.org/3/x5916e01.htm
fish_cf_kg <- 0.1/fish_percent
bread_percent <- 3.6/28 #usda
bread_cf_kg <- 0.1/bread_percent

meat_clean <- meat_raw %>% 
  clean_names() %>% 
  select(area, item, unit, y2003) %>% 
  filter(area == "United States of America") %>% 
  filter(unit == "kg CO2eq/kg product") %>% 
  rename(emission_factor = y2003) %>% 
  rename(ingredient = item) %>% 
  select(ingredient, emission_factor)

veggie_clean <- veggie_raw %>% 
  clean_names() %>% 
  filter(product %in% c("Wheat & Rye (Bread)", "Tomatoes", "Onions & Leeks", "Other Vegetables", "Cheese", "Fish (farmed)")) %>%
  mutate(emission_factor = case_when(
    product == "Wheat & Rye (Bread)" ~ median/bread_cf_kg,
    product == "Cheese" ~ median/cheese_cf_kg,
    product == "Fish (farmed)" ~ median/fish_cf_kg,
    TRUE ~ median
  )) %>% 
  rename(ingredient = product) %>% 
  select(ingredient, emission_factor)

ingredient_clean <- rbind(meat_clean, veggie_clean)

col_names <- ingredient_clean$ingredient

#Transpose the dataframe
ingredient_value <- ingredient_clean %>% 
  select(emission_factor)

ingredient_final <- as.data.frame(t(ingredient_value))

names(ingredient_final)<-col_names

ingredient_final <- ingredient_final %>% 
  clean_names()
```


